# Default gameserver world name
gameserverworldname: HBR01

# Item cooldowns (in seconds!)
smokescreen: 15
cloakduration: 10

# Grenade unpin and fuse times (in ticks!)
# FYI: 1 second = 20 game ticks
# FYI: 1 redstone tick = 2 game ticks, 4 redstone ticks = 2*4 game ticks.
grenade_unpinduration: 10
blindgrenade_fuseduration: 70

# Database setup
host: localhost
port: 3306
database: thehb_rewritten
table: player
username: root
password: