# Default gameserver world name
gameserverworldname: HBR01

# Item cooldowns (in seconds!)
smokescreen: 15
cloakduration: 10
grenadeusagedelay: 1.5
spectralstab_cooldown: 7.0

# Grenade unpin and fuse times (in ticks!)
  # FYI: 1 second = 20 game ticks
  # FYI: 1 redstone tick = 2 game ticks, 4 redstone ticks = 2*4 game ticks.
grenade_unpinduration: 10
grenade_fuseduration: 70

# Chemical grenade damage (0.0 - 20.0)
chemicalgrenade_damage: 7.0

# Chemical grenade damage radius
chemicalgrenade_damageradius: 6.0

# Assassin's Spectral Stab damage (0.0 - 20.0) (guaranteed to damage Herobrine this amount upon landing a Spectral Stab)
spectralstab_damage: 7.0

# Database setup
host: localhost
port: 3306
database: thehb_rewritten
table: player
username: root
password: