# Default gameserver world name
gameserverworldname: HBR01

# Item cooldowns (in seconds!)
smokescreen: 15.0
cloakduration: 15

# Database setup
host: localhost
port: 3306
database: thehb_rewritten
table: player
username: root
password: