name: HBRewrittenGS
version: ${project.version}
main: com.ben.hbrewrittengs.Main
api-version: 1.15
authors: [UndauntedPhish]
description: The gameserver plugin of The Herobrine Rewritten
depend: [ProtocolLib]
commands:
  class:
    description: Get a class.
  spawnshard:
    description: Spawns a shard at one of the shard spawn locations on the map

