name: HBRewrittenGS
version: ${project.version}
main: hbrewrittengs.hbrewrittengs.HBRewrittenGS
api-version: 1.13
authors: [UndauntedPhish]
description: The gameserver plugin of The Herobrine Rewritten
